# Generated by Django 5.2.8 on 2025-11-08 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('damage_type', models.CharField(max_length=100)),
                ('damage_description', models.TextField()),
                ('incident_date', models.DateField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deduction_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('wallet_deducted', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.policy')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
