# Generated by Django 5.2.8 on 2025-11-24 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', '-created_at'], name='claims_status_6be1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['user', 'status'], name='claims_user_id_7db873_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy'], name='claims_policy__d2422d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='claims_claim_n_b9e177_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['-created_at'], name='claims_created_19cf88_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['processed_by'], name='claims_process_455b7d_idx'),
        ),
    ]
