# Generated by Django 5.2.8 on 2025-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='deduction_percent',
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
