# Generated by Django 5.2.8 on 2025-11-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_remove_deduction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='payment_proof_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
