# Generated by Django 5.2.8 on 2025-11-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_claim_payment_date_claim_payment_proof_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='payment_proof_url',
        ),
        migrations.AddField(
            model_name='claim',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Payment details/notes', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='User WhatsApp number for payment notification', max_length=20, null=True),
        ),
    ]
