# Generated by Django 5.2.8 on 2026-01-07 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_remove_claim_payment_proof_url_claim_payment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='claim_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='claims.claim')),
            ],
            options={
                'db_table': 'claim_photos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
