# Generated by Django 5.2.8 on 2026-01-12 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_claimphoto'),
        ('policies', '0005_devicepackage_device_color'),
        ('stores', '0002_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='store',
            field=models.ForeignKey(blank=True, help_text="Store where this claim was created (from user's store)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['store', '-created_at'], name='claims_store_i_d75486_idx'),
        ),
    ]
