# Generated by Django 5.2.8 on 2026-01-12 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(help_text='Snapshot email saat log dibuat', max_length=254)),
                ('user_role', models.CharField(max_length=20)),
                ('store_code', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_CREATE', 'Create User'), ('USER_UPDATE', 'Update User'), ('USER_DELETE', 'Delete User'), ('USER_VERIFY', 'Verify User'), ('USER_ASSIGN_STORE', 'Assign User to Store'), ('POLICY_CREATE', 'Create Policy'), ('POLICY_UPDATE', 'Update Policy'), ('POLICY_ACTIVATE', 'Activate Policy'), ('POLICY_EXPIRE', 'Expire Policy'), ('CLAIM_CREATE', 'Create Claim'), ('CLAIM_APPROVE', 'Approve Claim'), ('CLAIM_REJECT', 'Reject Claim'), ('CLAIM_COMPLETE', 'Complete Claim'), ('CLAIM_ADMIN_CREATE', 'Admin Create Claim'), ('STORE_CREATE', 'Create Store'), ('STORE_UPDATE', 'Update Store'), ('STORE_DEACTIVATE', 'Deactivate Store'), ('DEVICE_CREATE', 'Create Device'), ('DEVICE_UPDATE', 'Update Device'), ('TIER_UPDATE', 'Update Policy Tier')], max_length=30)),
                ('target_model', models.CharField(help_text='Model yang diakses: User, Policy, Claim, etc', max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='ID object yang diakses', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, help_text='Data tambahan', null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='stores.store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'), models.Index(fields=['store', '-created_at'], name='activity_lo_store_i_2251e9_idx'), models.Index(fields=['action', '-created_at'], name='activity_lo_action_78df1b_idx'), models.Index(fields=['-created_at'], name='activity_lo_created_d8c226_idx')],
            },
        ),
    ]
