# Generated by Django 5.2.8 on 2026-01-12 11:26

from django.db import migrations, models


def set_registration_codes(apps, schema_editor):
    """Set registration codes for existing stores"""
    Store = apps.get_model('stores', 'Store')
    for store in Store.objects.all():
        if not store.registration_code:
            # Generate based on store code
            if 'KUA' in store.code.upper():
                store.registration_code = 'KUA001'
            elif 'OSP' in store.code.upper():
                store.registration_code = 'OSP001'
            else:
                # Generate random
                import random
                import string
                letters = ''.join(random.choices(string.ascii_uppercase, k=3))
                numbers = ''.join(random.choices(string.digits, k=3))
                store.registration_code = f"{letters}{numbers}"
            store.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_activitylog'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='store',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Kode registrasi untuk customer (contoh: OSP123)', max_length=10, default=''),
            preserve_default=False,
        ),
        # Step 2: Set registration codes
        migrations.RunPython(set_registration_codes),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='store',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Kode registrasi untuk customer (contoh: OSP123)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(help_text='Kode unik toko, contoh: SPC-OSP', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Nama toko, contoh: SPC Oesapa', max_length=100),
        ),
    ]
