# Generated by Django 5.2.8 on 2026-01-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_registration_code_alter_store_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Login Failed'), ('USER_CREATE', 'Create User'), ('USER_UPDATE', 'Update User'), ('USER_DELETE', 'Delete User'), ('USER_VERIFY', 'Verify User'), ('USER_ASSIGN_STORE', 'Assign User to Store'), ('POLICY_CREATE', 'Create Policy'), ('POLICY_UPDATE', 'Update Policy'), ('POLICY_ACTIVATE', 'Activate Policy'), ('POLICY_EXPIRE', 'Expire Policy'), ('CLAIM_CREATE', 'Create Claim'), ('CLAIM_UPDATE', 'Update Claim'), ('CLAIM_APPROVE', 'Approve Claim'), ('CLAIM_REJECT', 'Reject Claim'), ('CLAIM_COMPLETE', 'Complete Claim'), ('CLAIM_ADMIN_CREATE', 'Admin Create Claim'), ('STORE_CREATE', 'Create Store'), ('STORE_UPDATE', 'Update Store'), ('STORE_DEACTIVATE', 'Deactivate Store'), ('STORE_DELETE_PERMANENT', 'Delete Store Permanent'), ('STORE_RESET', 'Reset Store Data'), ('STORE_CREATE', 'Create Store'), ('STORE_UPDATE', 'Update Store'), ('STORE_DEACTIVATE', 'Deactivate Store'), ('DEVICE_CREATE', 'Create Device'), ('DEVICE_UPDATE', 'Update Device'), ('TIER_UPDATE', 'Update Policy Tier')], max_length=30),
        ),
    ]
