# Generated by Django 5.2.8 on 2025-11-08 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_brand', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('device_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('device_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'device_packages',
            },
        ),
        migrations.CreateModel(
            name='PolicyTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_name', models.CharField(max_length=50, unique=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('policy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('claim_deduction_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('policy_duration_days', models.IntegerField(default=365)),
                ('max_claims_per_year', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'policy_tiers',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('imei_number', models.CharField(max_length=20, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('policy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('claims_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.devicepackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.policytier')),
            ],
            options={
                'db_table': 'policies',
                'indexes': [models.Index(fields=['user', 'status'], name='policies_user_id_3c83de_idx'), models.Index(fields=['imei_number'], name='policies_imei_nu_3c7d41_idx')],
            },
        ),
    ]
