# Generated by Django 5.2.8 on 2025-11-24 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['expiry_date', 'status'], name='policies_expiry__074b7a_idx'),
        ),
    ]
