# Generated by Django 5.2.8 on 2025-11-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_add_expiry_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo policy untuk claim (sesuai harga HP)', max_digits=15),
        ),
    ]
