# Generated by Django 5.2.8 on 2025-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_policy_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepackage',
            name='device_category',
            field=models.CharField(choices=[('handphone', 'Handphone'), ('elektronik', 'Elektronik'), ('laptop', 'Laptop'), ('printer', 'Printer'), ('sepeda_listrik', 'Sepeda Listrik'), ('lainnya', 'Lainnya')], default='handphone', help_text='Kategori device (Handphone, Elektronik, dll)', max_length=50),
        ),
    ]
