# Generated by Django 5.2.8 on 2025-11-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_devicepackage_device_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepackage',
            name='device_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
