# Generated by Django 5.2.8 on 2026-01-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_devicepackage_device_color'),
        ('stores', '0004_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Toko yang menjual polis ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='stores.store'),
        ),
    ]
