# Generated by Django 5.2.8 on 2026-01-15 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_policy_store'),
        ('stores', '0004_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['store', 'status'], name='policies_store_i_a8b408_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['store', '-created_at'], name='policies_store_i_f5ff0d_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['-created_at'], name='policies_created_5d8705_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_policy__ca1bbf_idx'),
        ),
    ]
