# Generated by Django 5.2.8 on 2026-01-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stores', '0001_initial'),
        ('users', '0003_passwordreset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordreset',
            new_name='users_passw_user_id_db6c4c_idx',
            old_name='users_passw_user_id_5f0e51_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordreset',
            new_name='users_passw_otp_cod_508663_idx',
            old_name='users_passw_otp_cod_8c3e24_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('store_staff', 'Store Staff'), ('store_admin', 'Store Admin'), ('super_admin', 'Super Admin')], default='customer', help_text='Role user dalam sistem', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Toko tempat user bekerja/terdaftar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['store', 'role'], name='users_store_i_d40ba9_idx'),
        ),
    ]
