# Generated by Django 5.2.8 on 2025-11-24 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topuptransaction',
            index=models.Index(fields=['status', '-created_at'], name='topup_trans_status_ba2337_idx'),
        ),
        migrations.AddIndex(
            model_name='topuptransaction',
            index=models.Index(fields=['user', 'status'], name='topup_trans_user_id_7833a1_idx'),
        ),
        migrations.AddIndex(
            model_name='topuptransaction',
            index=models.Index(fields=['transaction_id'], name='topup_trans_transac_6782f1_idx'),
        ),
        migrations.AddIndex(
            model_name='topuptransaction',
            index=models.Index(fields=['-created_at'], name='topup_trans_created_d4a69d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallet_user_id_504f58_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['-balance'], name='wallet_balance_62f63f_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethistory',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_hist_wallet__abb933_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethistory',
            index=models.Index(fields=['transaction_type', '-created_at'], name='wallet_hist_transac_10de2c_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethistory',
            index=models.Index(fields=['-created_at'], name='wallet_hist_created_d4d707_idx'),
        ),
        migrations.AddIndex(
            model_name='wallethistory',
            index=models.Index(fields=['reference_id'], name='wallet_hist_referen_8c1252_idx'),
        ),
    ]
