# Generated by Django 5.2.8 on 2025-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_topuptransaction_topup_trans_status_ba2337_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuptransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
