"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# config/settings.py

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY: Read from environment variables (not hardcoded!)
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-me')
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # 'defender',  # Brute force protection (DISABLED - requires Redis)

    # Aplikasi Lokal Kita
    'users',
    'wallet',
    'policies',
    'claims',
    'admin_api',  # Admin API untuk dashboard
    'notifications',  # In-app notifications
    'stores',  # Multi-store system (NEW)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # Tambahkan CorsMiddleware di atas CommonMiddleware
    'corsheaders.middleware.CorsMiddleware', 
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Security: Brute force protection (DISABLED - requires Redis)
    # 'defender.middleware.FailedLoginMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# ===================================================================
# Konfigurasi untuk PostgreSQL - BACA DARI ENVIRONMENT VARIABLES
# ===================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'insurance_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),

        # OPTIMASI JUTAAN DATA:
        # Mengaktifkan connection pooling.
        # Django akan menyimpan koneksi yang sudah terbuka
        # alih-alih membuat koneksi baru setiap ada request.
        'CONN_MAX_AGE': 600, 
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    # ... (biarkan default) ...
]

# ===================================================================
# INI SANGAT PENTING: Memberi tahu Django untuk pakai model User kita
# Lakukan ini SEBELUM migrasi pertama.
# ===================================================================
AUTH_USER_MODEL = 'users.User'


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Makassar' # Atur zona waktu Anda (WITA)
USE_I18N = True
USE_TZ = True


# Caching Configuration (untuk handle jutaan data)
# ===================================================================
# Menggunakan in-memory cache (default)
# Untuk production, gunakan Redis/Memcached
# ===================================================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-phoneguard-cache',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Media files (User uploads - claim photos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# CLOUD STORAGE CONFIGURATION (For Production)
# ============================================================================
# Uncomment below to use AWS S3 for media files in production
# 
# Requirements:
#   pip install django-storages boto3
#
# Add to INSTALLED_APPS:
#   'storages',
#
# AWS S3 Configuration:
# ============================================================================
# USE_S3 = os.getenv('USE_S3', 'False') == 'True'
#
# if USE_S3:
#     # AWS Settings
#     AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
#     AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
#     AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
#     AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'ap-southeast-1')
#     AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
#     
#     # S3 File Settings
#     AWS_S3_OBJECT_PARAMETERS = {
#         'CacheControl': 'max-age=86400',  # 1 day cache
#     }
#     AWS_DEFAULT_ACL = 'public-read'
#     AWS_QUERYSTRING_AUTH = False
#     
#     # Use S3 for static and media files
#     STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
#     MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
#     
#     # Storage backends
#     DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#     STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# EMAIL CONFIGURATION (for Password Reset OTP)
# ============================================================================

# For TESTING: Print emails to console instead of sending
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For PRODUCTION: Uncomment below and configure with your email
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'  # Your email
# EMAIL_HOST_PASSWORD = 'your-app-password'  # Get from https://myaccount.google.com/apppasswords
# DEFAULT_FROM_EMAIL = 'PhoneGuard Insurance <noreply@phoneguard.com>'
# EMAIL_TIMEOUT = 10

# For TESTING: Use console backend (prints email to terminal)
DEFAULT_FROM_EMAIL = 'PhoneGuard Insurance <noreply@phoneguard.com>'

# ===================================================================
# Konfigurasi Tambahan
# ===================================================================

# Konfigurasi Django REST Framework (DRF)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Kita akan pakai Token Authentication (untuk login)
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Default-nya, semua endpoint butuh login
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Konfigurasi CORS (agar Flutter bisa akses API)
# Untuk sekarang, kita izinkan semua
CORS_ALLOW_ALL_ORIGINS = True

# ===================================================================
# SECURITY CONFIGURATION
# ===================================================================

# Django Defender - Brute Force Protection (Database mode - No Redis needed)
DEFENDER_STORE_ACCESS_ATTEMPTS = True  # Store in database
DEFENDER_USE_CELERY = False  # Don't use Celery
DEFENDER_REDIS_URL = None  # Explicitly set to None (use database)
DEFENDER_LOGIN_FAILURE_LIMIT = 5  # Max 5 failed attempts
DEFENDER_COOLOFF_TIME = 300  # 5 minutes lockout (300 seconds)
DEFENDER_LOCKOUT_TEMPLATE = None  # Return JSON for API
DEFENDER_BEHIND_REVERSE_PROXY = False
DEFENDER_DISABLE_IP_LOCKOUT = False
DEFENDER_DISABLE_USERNAME_LOCKOUT = False
DEFENDER_ACCESS_ATTEMPT_EXPIRATION = 24  # Hours

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 hours
